export interface City {
  code: string;
  name: string;
  pinyin: string;
  initial: string;
  province?: string;
}

export const cities: City[] = [
  // ========== 直辖市 ==========
  { code: "110000", name: "北京", pinyin: "beijing", initial: "bj", province: "北京市" },
  { code: "120000", name: "天津", pinyin: "tianjin", initial: "tj", province: "天津市" },
  { code: "310000", name: "上海", pinyin: "shanghai", initial: "sh", province: "上海市" },
  { code: "500000", name: "重庆", pinyin: "chongqing", initial: "cq", province: "重庆市" },

  // ========== 河北省 (11个) ==========
  { code: "130100", name: "石家庄", pinyin: "shijiazhuang", initial: "sjz", province: "河北省" },
  { code: "130200", name: "唐山", pinyin: "tangshan", initial: "ts", province: "河北省" },
  { code: "130300", name: "秦皇岛", pinyin: "qinhuangdao", initial: "qhd", province: "河北省" },
  { code: "130400", name: "邯郸", pinyin: "handan", initial: "hd", province: "河北省" },
  { code: "130500", name: "邢台", pinyin: "xingtai", initial: "xt", province: "河北省" },
  { code: "130600", name: "保定", pinyin: "baoding", initial: "bd", province: "河北省" },
  { code: "130700", name: "张家口", pinyin: "zhangjiakou", initial: "zjk", province: "河北省" },
  { code: "130800", name: "承德", pinyin: "chengde", initial: "cd", province: "河北省" },
  { code: "130900", name: "沧州", pinyin: "cangzhou", initial: "cz", province: "河北省" },
  { code: "131000", name: "廊坊", pinyin: "langfang", initial: "lf", province: "河北省" },
  { code: "131100", name: "衡水", pinyin: "hengshui", initial: "hs", province: "河北省" },

  // ========== 山西省 (11个) ==========
  { code: "140100", name: "太原", pinyin: "taiyuan", initial: "ty", province: "山西省" },
  { code: "140200", name: "大同", pinyin: "datong", initial: "dt", province: "山西省" },
  { code: "140300", name: "阳泉", pinyin: "yangquan", initial: "yq", province: "山西省" },
  { code: "140400", name: "长治", pinyin: "changzhi", initial: "cz", province: "山西省" },
  { code: "140500", name: "晋城", pinyin: "jincheng", initial: "jc", province: "山西省" },
  { code: "140600", name: "朔州", pinyin: "shuozhou", initial: "sz", province: "山西省" },
  { code: "140700", name: "晋中", pinyin: "jinzhong", initial: "jz", province: "山西省" },
  { code: "140800", name: "运城", pinyin: "yuncheng", initial: "yc", province: "山西省" },
  { code: "140900", name: "忻州", pinyin: "xinzhou", initial: "xz", province: "山西省" },
  { code: "141000", name: "临汾", pinyin: "linfen", initial: "lf", province: "山西省" },
  { code: "141100", name: "吕梁", pinyin: "lvliang", initial: "ll", province: "山西省" },

  // ========== 内蒙古自治区 (12个) ==========
  {
    code: "150100",
    name: "呼和浩特",
    pinyin: "huhehaote",
    initial: "hhht",
    province: "内蒙古自治区",
  },
  { code: "150200", name: "包头", pinyin: "baotou", initial: "bt", province: "内蒙古自治区" },
  { code: "150300", name: "乌海", pinyin: "wuhai", initial: "wh", province: "内蒙古自治区" },
  { code: "150400", name: "赤峰", pinyin: "chifeng", initial: "cf", province: "内蒙古自治区" },
  { code: "150500", name: "通辽", pinyin: "tongliao", initial: "tl", province: "内蒙古自治区" },
  {
    code: "150600",
    name: "鄂尔多斯",
    pinyin: "eerduosi",
    initial: "eeds",
    province: "内蒙古自治区",
  },
  {
    code: "150700",
    name: "呼伦贝尔",
    pinyin: "hulunbeier",
    initial: "hlbe",
    province: "内蒙古自治区",
  },
  {
    code: "150800",
    name: "巴彦淖尔",
    pinyin: "bayannaoer",
    initial: "byne",
    province: "内蒙古自治区",
  },
  {
    code: "150900",
    name: "乌兰察布",
    pinyin: "wulanchabu",
    initial: "wlcb",
    province: "内蒙古自治区",
  },
  {
    code: "152200",
    name: "兴安盟",
    pinyin: "xinganmeng",
    initial: "xam",
    province: "内蒙古自治区",
  },
  {
    code: "152500",
    name: "锡林郭勒",
    pinyin: "xilinguole",
    initial: "xlgl",
    province: "内蒙古自治区",
  },
  { code: "152900", name: "阿拉善", pinyin: "alashan", initial: "als", province: "内蒙古自治区" },

  // ========== 辽宁省 (14个) ==========
  { code: "210100", name: "沈阳", pinyin: "shenyang", initial: "sy", province: "辽宁省" },
  { code: "210200", name: "大连", pinyin: "dalian", initial: "dl", province: "辽宁省" },
  { code: "210300", name: "鞍山", pinyin: "anshan", initial: "as", province: "辽宁省" },
  { code: "210400", name: "抚顺", pinyin: "fushun", initial: "fs", province: "辽宁省" },
  { code: "210500", name: "本溪", pinyin: "benxi", initial: "bx", province: "辽宁省" },
  { code: "210600", name: "丹东", pinyin: "dandong", initial: "dd", province: "辽宁省" },
  { code: "210700", name: "锦州", pinyin: "jinzhou", initial: "jz", province: "辽宁省" },
  { code: "210800", name: "营口", pinyin: "yingkou", initial: "yk", province: "辽宁省" },
  { code: "210900", name: "阜新", pinyin: "fuxin", initial: "fx", province: "辽宁省" },
  { code: "211000", name: "辽阳", pinyin: "liaoyang", initial: "ly", province: "辽宁省" },
  { code: "211100", name: "盘锦", pinyin: "panjin", initial: "pj", province: "辽宁省" },
  { code: "211200", name: "铁岭", pinyin: "tieling", initial: "tl", province: "辽宁省" },
  { code: "211300", name: "朝阳", pinyin: "chaoyang", initial: "cy", province: "辽宁省" },
  { code: "211400", name: "葫芦岛", pinyin: "huludao", initial: "hld", province: "辽宁省" },

  // ========== 吉林省 (9个) ==========
  { code: "220100", name: "长春", pinyin: "changchun", initial: "cc", province: "吉林省" },
  { code: "220200", name: "吉林", pinyin: "jilin", initial: "jl", province: "吉林省" },
  { code: "220300", name: "四平", pinyin: "siping", initial: "sp", province: "吉林省" },
  { code: "220400", name: "辽源", pinyin: "liaoyuan", initial: "ly", province: "吉林省" },
  { code: "220500", name: "通化", pinyin: "tonghua", initial: "th", province: "吉林省" },
  { code: "220600", name: "白山", pinyin: "baishan", initial: "bs", province: "吉林省" },
  { code: "220700", name: "松原", pinyin: "songyuan", initial: "sy", province: "吉林省" },
  { code: "220800", name: "白城", pinyin: "baicheng", initial: "bc", province: "吉林省" },
  { code: "222400", name: "延边", pinyin: "yanbian", initial: "yb", province: "吉林省" },

  // ========== 黑龙江省 (13个) ==========
  { code: "230100", name: "哈尔滨", pinyin: "haerbin", initial: "heb", province: "黑龙江省" },
  { code: "230200", name: "齐齐哈尔", pinyin: "qiqihaer", initial: "qqhe", province: "黑龙江省" },
  { code: "230300", name: "鸡西", pinyin: "jixi", initial: "jx", province: "黑龙江省" },
  { code: "230400", name: "鹤岗", pinyin: "hegang", initial: "hg", province: "黑龙江省" },
  { code: "230500", name: "双鸭山", pinyin: "shuangyashan", initial: "sys", province: "黑龙江省" },
  { code: "230600", name: "大庆", pinyin: "daqing", initial: "dq", province: "黑龙江省" },
  { code: "230700", name: "伊春", pinyin: "yichun", initial: "yc", province: "黑龙江省" },
  { code: "230800", name: "佳木斯", pinyin: "jiamusi", initial: "jms", province: "黑龙江省" },
  { code: "230900", name: "七台河", pinyin: "qitaihe", initial: "qth", province: "黑龙江省" },
  { code: "231000", name: "牡丹江", pinyin: "mudanjiang", initial: "mdj", province: "黑龙江省" },
  { code: "231100", name: "黑河", pinyin: "heihe", initial: "hh", province: "黑龙江省" },
  { code: "231200", name: "绥化", pinyin: "suihua", initial: "sh", province: "黑龙江省" },
  {
    code: "232700",
    name: "大兴安岭",
    pinyin: "daxinganling",
    initial: "dxal",
    province: "黑龙江省",
  },

  // ========== 江苏省 (13个) ==========
  { code: "320100", name: "南京", pinyin: "nanjing", initial: "nj", province: "江苏省" },
  { code: "320200", name: "无锡", pinyin: "wuxi", initial: "wx", province: "江苏省" },
  { code: "320300", name: "徐州", pinyin: "xuzhou", initial: "xz", province: "江苏省" },
  { code: "320400", name: "常州", pinyin: "changzhou", initial: "cz", province: "江苏省" },
  { code: "320500", name: "苏州", pinyin: "suzhou", initial: "sz", province: "江苏省" },
  { code: "320600", name: "南通", pinyin: "nantong", initial: "nt", province: "江苏省" },
  { code: "320700", name: "连云港", pinyin: "lianyungang", initial: "lyg", province: "江苏省" },
  { code: "320800", name: "淮安", pinyin: "huaian", initial: "ha", province: "江苏省" },
  { code: "320900", name: "盐城", pinyin: "yancheng", initial: "yc", province: "江苏省" },
  { code: "321000", name: "扬州", pinyin: "yangzhou", initial: "yz", province: "江苏省" },
  { code: "321100", name: "镇江", pinyin: "zhenjiang", initial: "zj", province: "江苏省" },
  { code: "321200", name: "泰州", pinyin: "taizhou", initial: "tz", province: "江苏省" },
  { code: "321300", name: "宿迁", pinyin: "suqian", initial: "sq", province: "江苏省" },

  // ========== 浙江省 (11个) ==========
  { code: "330100", name: "杭州", pinyin: "hangzhou", initial: "hz", province: "浙江省" },
  { code: "330200", name: "宁波", pinyin: "ningbo", initial: "nb", province: "浙江省" },
  { code: "330300", name: "温州", pinyin: "wenzhou", initial: "wz", province: "浙江省" },
  { code: "330400", name: "嘉兴", pinyin: "jiaxing", initial: "jx", province: "浙江省" },
  { code: "330500", name: "湖州", pinyin: "huzhou", initial: "hz", province: "浙江省" },
  { code: "330600", name: "绍兴", pinyin: "shaoxing", initial: "sx", province: "浙江省" },
  { code: "330700", name: "金华", pinyin: "jinhua", initial: "jh", province: "浙江省" },
  { code: "330800", name: "衢州", pinyin: "quzhou", initial: "qz", province: "浙江省" },
  { code: "330900", name: "舟山", pinyin: "zhoushan", initial: "zs", province: "浙江省" },
  { code: "331000", name: "台州", pinyin: "taizhou", initial: "tz", province: "浙江省" },
  { code: "331100", name: "丽水", pinyin: "lishui", initial: "ls", province: "浙江省" },

  // ========== 安徽省 (16个) ==========
  { code: "340100", name: "合肥", pinyin: "hefei", initial: "hf", province: "安徽省" },
  { code: "340200", name: "芜湖", pinyin: "wuhu", initial: "wh", province: "安徽省" },
  { code: "340300", name: "蚌埠", pinyin: "bengbu", initial: "bb", province: "安徽省" },
  { code: "340400", name: "淮南", pinyin: "huainan", initial: "hn", province: "安徽省" },
  { code: "340500", name: "马鞍山", pinyin: "maanshan", initial: "mas", province: "安徽省" },
  { code: "340600", name: "淮北", pinyin: "huaibei", initial: "hb", province: "安徽省" },
  { code: "340700", name: "铜陵", pinyin: "tongling", initial: "tl", province: "安徽省" },
  { code: "340800", name: "安庆", pinyin: "anqing", initial: "aq", province: "安徽省" },
  { code: "341000", name: "黄山", pinyin: "huangshan", initial: "hs", province: "安徽省" },
  { code: "341100", name: "滁州", pinyin: "chuzhou", initial: "cz", province: "安徽省" },
  { code: "341200", name: "阜阳", pinyin: "fuyang", initial: "fy", province: "安徽省" },
  { code: "341300", name: "宿州", pinyin: "suzhou", initial: "sz", province: "安徽省" },
  { code: "341500", name: "六安", pinyin: "luan", initial: "la", province: "安徽省" },
  { code: "341600", name: "亳州", pinyin: "bozhou", initial: "bz", province: "安徽省" },
  { code: "341700", name: "池州", pinyin: "chizhou", initial: "cz", province: "安徽省" },
  { code: "341800", name: "宣城", pinyin: "xuancheng", initial: "xc", province: "安徽省" },

  // ========== 福建省 (9个) ==========
  { code: "350100", name: "福州", pinyin: "fuzhou", initial: "fz", province: "福建省" },
  { code: "350200", name: "厦门", pinyin: "xiamen", initial: "xm", province: "福建省" },
  { code: "350300", name: "莆田", pinyin: "putian", initial: "pt", province: "福建省" },
  { code: "350400", name: "三明", pinyin: "sanming", initial: "sm", province: "福建省" },
  { code: "350500", name: "泉州", pinyin: "quanzhou", initial: "qz", province: "福建省" },
  { code: "350600", name: "漳州", pinyin: "zhangzhou", initial: "zz", province: "福建省" },
  { code: "350700", name: "南平", pinyin: "nanping", initial: "np", province: "福建省" },
  { code: "350800", name: "龙岩", pinyin: "longyan", initial: "ly", province: "福建省" },
  { code: "350900", name: "宁德", pinyin: "ningde", initial: "nd", province: "福建省" },

  // ========== 江西省 (11个) ==========
  { code: "360100", name: "南昌", pinyin: "nanchang", initial: "nc", province: "江西省" },
  { code: "360200", name: "景德镇", pinyin: "jingdezhen", initial: "jdz", province: "江西省" },
  { code: "360300", name: "萍乡", pinyin: "pingxiang", initial: "px", province: "江西省" },
  { code: "360400", name: "九江", pinyin: "jiujiang", initial: "jj", province: "江西省" },
  { code: "360500", name: "新余", pinyin: "xinyu", initial: "xy", province: "江西省" },
  { code: "360600", name: "鹰潭", pinyin: "yingtan", initial: "yt", province: "江西省" },
  { code: "360700", name: "赣州", pinyin: "ganzhou", initial: "gz", province: "江西省" },
  { code: "360800", name: "吉安", pinyin: "jian", initial: "ja", province: "江西省" },
  { code: "360900", name: "宜春", pinyin: "yichun", initial: "yc", province: "江西省" },
  { code: "361000", name: "抚州", pinyin: "fuzhou", initial: "fz", province: "江西省" },
  { code: "361100", name: "上饶", pinyin: "shangrao", initial: "sr", province: "江西省" },

  // ========== 山东省 (16个) ==========
  { code: "370100", name: "济南", pinyin: "jinan", initial: "jn", province: "山东省" },
  { code: "370200", name: "青岛", pinyin: "qingdao", initial: "qd", province: "山东省" },
  { code: "370300", name: "淄博", pinyin: "zibo", initial: "zb", province: "山东省" },
  { code: "370400", name: "枣庄", pinyin: "zaozhuang", initial: "zz", province: "山东省" },
  { code: "370500", name: "东营", pinyin: "dongying", initial: "dy", province: "山东省" },
  { code: "370600", name: "烟台", pinyin: "yantai", initial: "yt", province: "山东省" },
  { code: "370700", name: "潍坊", pinyin: "weifang", initial: "wf", province: "山东省" },
  { code: "370800", name: "济宁", pinyin: "jining", initial: "jn", province: "山东省" },
  { code: "370900", name: "泰安", pinyin: "taian", initial: "ta", province: "山东省" },
  { code: "371000", name: "威海", pinyin: "weihai", initial: "wh", province: "山东省" },
  { code: "371100", name: "日照", pinyin: "rizhao", initial: "rz", province: "山东省" },
  { code: "371300", name: "临沂", pinyin: "linyi", initial: "ly", province: "山东省" },
  { code: "371400", name: "德州", pinyin: "dezhou", initial: "dz", province: "山东省" },
  { code: "371500", name: "聊城", pinyin: "liaocheng", initial: "lc", province: "山东省" },
  { code: "371600", name: "滨州", pinyin: "binzhou", initial: "bz", province: "山东省" },
  { code: "371700", name: "菏泽", pinyin: "heze", initial: "hz", province: "山东省" },
  // ========== 河南省 (17个) ==========
  { code: "410100", name: "郑州", pinyin: "zhengzhou", initial: "zz", province: "河南省" },
  { code: "410200", name: "开封", pinyin: "kaifeng", initial: "kf", province: "河南省" },
  { code: "410300", name: "洛阳", pinyin: "luoyang", initial: "ly", province: "河南省" },
  { code: "410400", name: "平顶山", pinyin: "pingdingshan", initial: "pds", province: "河南省" },
  { code: "410500", name: "安阳", pinyin: "anyang", initial: "ay", province: "河南省" },
  { code: "410600", name: "鹤壁", pinyin: "hebi", initial: "hb", province: "河南省" },
  { code: "410700", name: "新乡", pinyin: "xinxiang", initial: "xx", province: "河南省" },
  { code: "410800", name: "焦作", pinyin: "jiaozuo", initial: "jz", province: "河南省" },
  { code: "410900", name: "濮阳", pinyin: "puyang", initial: "py", province: "河南省" },
  { code: "411000", name: "许昌", pinyin: "xuchang", initial: "xc", province: "河南省" },
  { code: "411100", name: "漯河", pinyin: "luohe", initial: "lh", province: "河南省" },
  { code: "411200", name: "三门峡", pinyin: "sanmenxia", initial: "smx", province: "河南省" },
  { code: "411300", name: "南阳", pinyin: "nanyang", initial: "ny", province: "河南省" },
  { code: "411400", name: "商丘", pinyin: "shangqiu", initial: "sq", province: "河南省" },
  { code: "411500", name: "信阳", pinyin: "xinyang", initial: "xy", province: "河南省" },
  { code: "411600", name: "周口", pinyin: "zhoukou", initial: "zk", province: "河南省" },
  { code: "411700", name: "驻马店", pinyin: "zhumadian", initial: "zmd", province: "河南省" },

  // ========== 湖北省 (13个) ==========
  { code: "420100", name: "武汉", pinyin: "wuhan", initial: "wh", province: "湖北省" },
  { code: "420200", name: "黄石", pinyin: "huangshi", initial: "hs", province: "湖北省" },
  { code: "420300", name: "十堰", pinyin: "shiyan", initial: "sy", province: "湖北省" },
  { code: "420500", name: "宜昌", pinyin: "yichang", initial: "yc", province: "湖北省" },
  { code: "420600", name: "襄阳", pinyin: "xiangyang", initial: "xy", province: "湖北省" },
  { code: "420700", name: "鄂州", pinyin: "ezhou", initial: "ez", province: "湖北省" },
  { code: "420800", name: "荆门", pinyin: "jingmen", initial: "jm", province: "湖北省" },
  { code: "420900", name: "孝感", pinyin: "xiaogan", initial: "xg", province: "湖北省" },
  { code: "421000", name: "荆州", pinyin: "jingzhou", initial: "jz", province: "湖北省" },
  { code: "421100", name: "黄冈", pinyin: "huanggang", initial: "hg", province: "湖北省" },
  { code: "421200", name: "咸宁", pinyin: "xianning", initial: "xn", province: "湖北省" },
  { code: "421300", name: "随州", pinyin: "suizhou", initial: "sz", province: "湖北省" },
  { code: "422800", name: "恩施", pinyin: "enshi", initial: "es", province: "湖北省" },

  // ========== 湖南省 (14个) ==========
  { code: "430100", name: "长沙", pinyin: "changsha", initial: "cs", province: "湖南省" },
  { code: "430200", name: "株洲", pinyin: "zhuzhou", initial: "zz", province: "湖南省" },
  { code: "430300", name: "湘潭", pinyin: "xiangtan", initial: "xt", province: "湖南省" },
  { code: "430400", name: "衡阳", pinyin: "hengyang", initial: "hy", province: "湖南省" },
  { code: "430500", name: "邵阳", pinyin: "shaoyang", initial: "sy", province: "湖南省" },
  { code: "430600", name: "岳阳", pinyin: "yueyang", initial: "yy", province: "湖南省" },
  { code: "430700", name: "常德", pinyin: "changde", initial: "cd", province: "湖南省" },
  { code: "430800", name: "张家界", pinyin: "zhangjiajie", initial: "zjj", province: "湖南省" },
  { code: "430900", name: "益阳", pinyin: "yiyang", initial: "yy", province: "湖南省" },
  { code: "431000", name: "郴州", pinyin: "chenzhou", initial: "cz", province: "湖南省" },
  { code: "431100", name: "永州", pinyin: "yongzhou", initial: "yz", province: "湖南省" },
  { code: "431200", name: "怀化", pinyin: "huaihua", initial: "hh", province: "湖南省" },
  { code: "431300", name: "娄底", pinyin: "loudi", initial: "ld", province: "湖南省" },
  { code: "433100", name: "湘西", pinyin: "xiangxi", initial: "xx", province: "湖南省" },
  // ========== 广东省 (21个) ==========
  { code: "440100", name: "广州", pinyin: "guangzhou", initial: "gz", province: "广东省" },
  { code: "440200", name: "韶关", pinyin: "shaoguan", initial: "sg", province: "广东省" },
  { code: "440300", name: "深圳", pinyin: "shenzhen", initial: "sz", province: "广东省" },
  { code: "440400", name: "珠海", pinyin: "zhuhai", initial: "zh", province: "广东省" },
  { code: "440500", name: "汕头", pinyin: "shantou", initial: "st", province: "广东省" },
  { code: "440600", name: "佛山", pinyin: "foshan", initial: "fs", province: "广东省" },
  { code: "440700", name: "江门", pinyin: "jiangmen", initial: "jm", province: "广东省" },
  { code: "440800", name: "湛江", pinyin: "zhanjiang", initial: "zj", province: "广东省" },
  { code: "440900", name: "茂名", pinyin: "maoming", initial: "mm", province: "广东省" },
  { code: "441200", name: "肇庆", pinyin: "zhaoqing", initial: "zq", province: "广东省" },
  { code: "441300", name: "惠州", pinyin: "huizhou", initial: "hz", province: "广东省" },
  { code: "441400", name: "梅州", pinyin: "meizhou", initial: "mz", province: "广东省" },
  { code: "441500", name: "汕尾", pinyin: "shanwei", initial: "sw", province: "广东省" },
  { code: "441600", name: "河源", pinyin: "heyuan", initial: "hy", province: "广东省" },
  { code: "441700", name: "阳江", pinyin: "yangjiang", initial: "yj", province: "广东省" },
  { code: "441800", name: "清远", pinyin: "qingyuan", initial: "qy", province: "广东省" },
  { code: "441900", name: "东莞", pinyin: "dongguan", initial: "dg", province: "广东省" },
  { code: "442000", name: "中山", pinyin: "zhongshan", initial: "zs", province: "广东省" },
  { code: "445100", name: "潮州", pinyin: "chaozhou", initial: "cz", province: "广东省" },
  { code: "445200", name: "揭阳", pinyin: "jieyang", initial: "jy", province: "广东省" },
  { code: "445300", name: "云浮", pinyin: "yunfu", initial: "yf", province: "广东省" },
  // ========== 广西壮族自治区 (14个) ==========
  { code: "450100", name: "南宁", pinyin: "nanning", initial: "nn", province: "广西壮族自治区" },
  { code: "450200", name: "柳州", pinyin: "liuzhou", initial: "lz", province: "广西壮族自治区" },
  { code: "450300", name: "桂林", pinyin: "guilin", initial: "gl", province: "广西壮族自治区" },
  { code: "450400", name: "梧州", pinyin: "wuzhou", initial: "wz", province: "广西壮族自治区" },
  { code: "450500", name: "北海", pinyin: "beihai", initial: "bh", province: "广西壮族自治区" },
  {
    code: "450600",
    name: "防城港",
    pinyin: "fangchenggang",
    initial: "fcg",
    province: "广西壮族自治区",
  },
  { code: "450700", name: "钦州", pinyin: "qinzhou", initial: "qz", province: "广西壮族自治区" },
  { code: "450800", name: "贵港", pinyin: "guigang", initial: "gg", province: "广西壮族自治区" },
  { code: "450900", name: "玉林", pinyin: "yulin", initial: "yl", province: "广西壮族自治区" },
  { code: "451000", name: "百色", pinyin: "baise", initial: "bs", province: "广西壮族自治区" },
  { code: "451100", name: "贺州", pinyin: "hezhou", initial: "hz", province: "广西壮族自治区" },
  { code: "451200", name: "河池", pinyin: "hechi", initial: "hc", province: "广西壮族自治区" },
  { code: "451300", name: "来宾", pinyin: "laibin", initial: "lb", province: "广西壮族自治区" },
  { code: "451400", name: "崇左", pinyin: "chongzuo", initial: "cz", province: "广西壮族自治区" },

  // ========== 海南省 (4个) ==========
  { code: "460100", name: "海口", pinyin: "haikou", initial: "hk", province: "海南省" },
  { code: "460200", name: "三亚", pinyin: "sanya", initial: "sy", province: "海南省" },
  { code: "460300", name: "三沙", pinyin: "sansha", initial: "ss", province: "海南省" },
  { code: "460400", name: "儋州", pinyin: "danzhou", initial: "dz", province: "海南省" },
  // ========== 四川省 (21个) ==========
  { code: "510100", name: "成都", pinyin: "chengdu", initial: "cd", province: "四川省" },
  { code: "510300", name: "自贡", pinyin: "zigong", initial: "zg", province: "四川省" },
  { code: "510400", name: "攀枝花", pinyin: "panzhihua", initial: "pzh", province: "四川省" },
  { code: "510500", name: "泸州", pinyin: "luzhou", initial: "lz", province: "四川省" },
  { code: "510600", name: "德阳", pinyin: "deyang", initial: "dy", province: "四川省" },
  { code: "510700", name: "绵阳", pinyin: "mianyang", initial: "my", province: "四川省" },
  { code: "510800", name: "广元", pinyin: "guangyuan", initial: "gy", province: "四川省" },
  { code: "510900", name: "遂宁", pinyin: "suining", initial: "sn", province: "四川省" },
  { code: "511000", name: "内江", pinyin: "neijiang", initial: "nj", province: "四川省" },
  { code: "511100", name: "乐山", pinyin: "leshan", initial: "ls", province: "四川省" },
  { code: "511300", name: "南充", pinyin: "nanchong", initial: "nc", province: "四川省" },
  { code: "511400", name: "眉山", pinyin: "meishan", initial: "ms", province: "四川省" },
  { code: "511500", name: "宜宾", pinyin: "yibin", initial: "yb", province: "四川省" },
  { code: "511600", name: "广安", pinyin: "guangan", initial: "ga", province: "四川省" },
  { code: "511700", name: "达州", pinyin: "dazhou", initial: "dz", province: "四川省" },
  { code: "511800", name: "雅安", pinyin: "yaan", initial: "ya", province: "四川省" },
  { code: "511900", name: "巴中", pinyin: "bazhong", initial: "bz", province: "四川省" },
  { code: "512000", name: "资阳", pinyin: "ziyang", initial: "zy", province: "四川省" },
  { code: "513200", name: "阿坝", pinyin: "aba", initial: "ab", province: "四川省" },
  { code: "513300", name: "甘孜", pinyin: "ganzi", initial: "gz", province: "四川省" },
  { code: "513400", name: "凉山", pinyin: "liangshan", initial: "ls", province: "四川省" },
  // ========== 贵州省 (9个) ==========
  { code: "520100", name: "贵阳", pinyin: "guiyang", initial: "gy", province: "贵州省" },
  { code: "520200", name: "六盘水", pinyin: "liupanshui", initial: "lps", province: "贵州省" },
  { code: "520300", name: "遵义", pinyin: "zunyi", initial: "zy", province: "贵州省" },
  { code: "520400", name: "安顺", pinyin: "anshun", initial: "as", province: "贵州省" },
  { code: "520500", name: "毕节", pinyin: "bijie", initial: "bj", province: "贵州省" },
  { code: "520600", name: "铜仁", pinyin: "tongren", initial: "tr", province: "贵州省" },
  { code: "522300", name: "黔西南", pinyin: "qianxinan", initial: "qxn", province: "贵州省" },
  { code: "522600", name: "黔东南", pinyin: "qiandongnan", initial: "qdn", province: "贵州省" },
  { code: "522700", name: "黔南", pinyin: "qiannan", initial: "qn", province: "贵州省" },

  // ========== 云南省 (16个) ==========
  { code: "530100", name: "昆明", pinyin: "kunming", initial: "km", province: "云南省" },
  { code: "530300", name: "曲靖", pinyin: "qujing", initial: "qj", province: "云南省" },
  { code: "530400", name: "玉溪", pinyin: "yuxi", initial: "yx", province: "云南省" },
  { code: "530500", name: "保山", pinyin: "baoshan", initial: "bs", province: "云南省" },
  { code: "530600", name: "昭通", pinyin: "zhaotong", initial: "zt", province: "云南省" },
  { code: "530700", name: "丽江", pinyin: "lijiang", initial: "lj", province: "云南省" },
  { code: "530800", name: "普洱", pinyin: "puer", initial: "pe", province: "云南省" },
  { code: "530900", name: "临沧", pinyin: "lincang", initial: "lc", province: "云南省" },
  { code: "532300", name: "楚雄", pinyin: "chuxiong", initial: "cx", province: "云南省" },
  { code: "532500", name: "红河", pinyin: "honghe", initial: "hh", province: "云南省" },
  { code: "532600", name: "文山", pinyin: "wenshan", initial: "ws", province: "云南省" },
  {
    code: "532800",
    name: "西双版纳",
    pinyin: "xishuangbanna",
    initial: "xsbn",
    province: "云南省",
  },
  { code: "532900", name: "大理", pinyin: "dali", initial: "dl", province: "云南省" },
  { code: "533100", name: "德宏", pinyin: "dehong", initial: "dh", province: "云南省" },
  { code: "533300", name: "怒江", pinyin: "nujiang", initial: "nj", province: "云南省" },
  { code: "533400", name: "迪庆", pinyin: "diqing", initial: "dq", province: "云南省" },
  // ========== 西藏自治区 (7个) ==========
  { code: "540100", name: "拉萨", pinyin: "lasa", initial: "ls", province: "西藏自治区" },
  { code: "540200", name: "日喀则", pinyin: "rikaze", initial: "rkz", province: "西藏自治区" },
  { code: "540300", name: "昌都", pinyin: "changdu", initial: "cd", province: "西藏自治区" },
  { code: "540400", name: "林芝", pinyin: "linzhi", initial: "lz", province: "西藏自治区" },
  { code: "540500", name: "山南", pinyin: "shannan", initial: "sn", province: "西藏自治区" },
  { code: "540600", name: "那曲", pinyin: "naqu", initial: "nq", province: "西藏自治区" },
  { code: "542500", name: "阿里", pinyin: "ali", initial: "al", province: "西藏自治区" },

  // ========== 陕西省 (10个) ==========
  { code: "610100", name: "西安", pinyin: "xian", initial: "xa", province: "陕西省" },
  { code: "610200", name: "铜川", pinyin: "tongchuan", initial: "tc", province: "陕西省" },
  { code: "610300", name: "宝鸡", pinyin: "baoji", initial: "bj", province: "陕西省" },
  { code: "610400", name: "咸阳", pinyin: "xianyang", initial: "xy", province: "陕西省" },
  { code: "610500", name: "渭南", pinyin: "weinan", initial: "wn", province: "陕西省" },
  { code: "610600", name: "延安", pinyin: "yanan", initial: "ya", province: "陕西省" },
  { code: "610700", name: "汉中", pinyin: "hanzhong", initial: "hz", province: "陕西省" },
  { code: "610800", name: "榆林", pinyin: "yulin", initial: "yl", province: "陕西省" },
  { code: "610900", name: "安康", pinyin: "ankang", initial: "ak", province: "陕西省" },
  { code: "611000", name: "商洛", pinyin: "shangluo", initial: "sl", province: "陕西省" },

  // ========== 甘肃省 (14个) ==========
  { code: "620100", name: "兰州", pinyin: "lanzhou", initial: "lz", province: "甘肃省" },
  { code: "620200", name: "嘉峪关", pinyin: "jiayuguan", initial: "jyg", province: "甘肃省" },
  { code: "620300", name: "金昌", pinyin: "jinchang", initial: "jc", province: "甘肃省" },
  { code: "620400", name: "白银", pinyin: "baiyin", initial: "by", province: "甘肃省" },
  { code: "620500", name: "天水", pinyin: "tianshui", initial: "ts", province: "甘肃省" },
  { code: "620600", name: "武威", pinyin: "wuwei", initial: "ww", province: "甘肃省" },
  { code: "620700", name: "张掖", pinyin: "zhangye", initial: "zy", province: "甘肃省" },
  { code: "620800", name: "平凉", pinyin: "pingliang", initial: "pl", province: "甘肃省" },
  { code: "620900", name: "酒泉", pinyin: "jiuquan", initial: "jq", province: "甘肃省" },
  { code: "621000", name: "庆阳", pinyin: "qingyang", initial: "qy", province: "甘肃省" },
  { code: "621100", name: "定西", pinyin: "dingxi", initial: "dx", province: "甘肃省" },
  { code: "621200", name: "陇南", pinyin: "longnan", initial: "ln", province: "甘肃省" },
  { code: "622900", name: "临夏", pinyin: "linxia", initial: "lx", province: "甘肃省" },
  { code: "623000", name: "甘南", pinyin: "gannan", initial: "gn", province: "甘肃省" },

  // ========== 青海省 (8个) ==========
  { code: "630100", name: "西宁", pinyin: "xining", initial: "xn", province: "青海省" },
  { code: "630200", name: "海东", pinyin: "haidong", initial: "hd", province: "青海省" },
  { code: "632200", name: "海北", pinyin: "haibei", initial: "hb", province: "青海省" },
  { code: "632300", name: "黄南", pinyin: "huangnan", initial: "hn", province: "青海省" },
  { code: "632500", name: "海南", pinyin: "hainan", initial: "hn", province: "青海省" },
  { code: "632600", name: "果洛", pinyin: "guoluo", initial: "gl", province: "青海省" },
  { code: "632700", name: "玉树", pinyin: "yushu", initial: "ys", province: "青海省" },
  { code: "632800", name: "海西", pinyin: "haixi", initial: "hx", province: "青海省" },

  // ========== 宁夏回族自治区 (5个) ==========
  { code: "640100", name: "银川", pinyin: "yinchuan", initial: "yc", province: "宁夏回族自治区" },
  {
    code: "640200",
    name: "石嘴山",
    pinyin: "shizuishan",
    initial: "szs",
    province: "宁夏回族自治区",
  },
  { code: "640300", name: "吴忠", pinyin: "wuzhong", initial: "wz", province: "宁夏回族自治区" },
  { code: "640400", name: "固原", pinyin: "guyuan", initial: "gy", province: "宁夏回族自治区" },
  { code: "640500", name: "中卫", pinyin: "zhongwei", initial: "zw", province: "宁夏回族自治区" },

  // ========== 新疆维吾尔自治区 (14个) ==========
  {
    code: "650100",
    name: "乌鲁木齐",
    pinyin: "wulumuqi",
    initial: "wlmq",
    province: "新疆维吾尔自治区",
  },
  {
    code: "650200",
    name: "克拉玛依",
    pinyin: "kelamayi",
    initial: "klmy",
    province: "新疆维吾尔自治区",
  },
  {
    code: "650400",
    name: "吐鲁番",
    pinyin: "tulufan",
    initial: "tlf",
    province: "新疆维吾尔自治区",
  },
  { code: "650500", name: "哈密", pinyin: "hami", initial: "hm", province: "新疆维吾尔自治区" },
  { code: "652300", name: "昌吉", pinyin: "changji", initial: "cj", province: "新疆维吾尔自治区" },
  {
    code: "652700",
    name: "博尔塔拉",
    pinyin: "boertala",
    initial: "betl",
    province: "新疆维吾尔自治区",
  },
  {
    code: "652800",
    name: "巴音郭楞",
    pinyin: "bayinguoleng",
    initial: "bygl",
    province: "新疆维吾尔自治区",
  },
  { code: "652900", name: "阿克苏", pinyin: "akesu", initial: "aks", province: "新疆维吾尔自治区" },
  {
    code: "653000",
    name: "克孜勒苏",
    pinyin: "kezilesu",
    initial: "kzls",
    province: "新疆维吾尔自治区",
  },
  { code: "653100", name: "喀什", pinyin: "kashen", initial: "ks", province: "新疆维吾尔自治区" },
  { code: "653200", name: "和田", pinyin: "hetian", initial: "ht", province: "新疆维吾尔自治区" },
  { code: "654000", name: "伊犁", pinyin: "yili", initial: "yl", province: "新疆维吾尔自治区" },
  { code: "654200", name: "塔城", pinyin: "tacheng", initial: "tc", province: "新疆维吾尔自治区" },
  {
    code: "654300",
    name: "阿勒泰",
    pinyin: "aletai",
    initial: "alt",
    province: "新疆维吾尔自治区",
  },
  // ========== 台湾省 (6个) ==========
  { code: "710100", name: "台北", pinyin: "taibei", initial: "tb", province: "台湾省" },
  { code: "710200", name: "高雄", pinyin: "gaoxiong", initial: "gx", province: "台湾省" },
  { code: "710300", name: "台南", pinyin: "tainan", initial: "tn", province: "台湾省" },
  { code: "710400", name: "台中", pinyin: "taizhong", initial: "tz", province: "台湾省" },
  { code: "710500", name: "基隆", pinyin: "jilong", initial: "jl", province: "台湾省" },
  { code: "710600", name: "新竹", pinyin: "xinzhu", initial: "xz", province: "台湾省" },

  // ========== 香港、澳门 ==========
  { code: "810000", name: "香港", pinyin: "xianggang", initial: "xg", province: "香港特别行政区" },
  { code: "820000", name: "澳门", pinyin: "aomen", initial: "am", province: "澳门特别行政区" },
];
// 搜索函数 - 支持拼音、首字母、中文搜索
export const searchCity = (cityData: string) => {
  if (!cityData || cityData.trim() === "") {
    return [];
  }

  const keyword = cityData.trim().toLowerCase();
  const isPinyin = /^[a-zA-Z]+$/.test(keyword);

  const citiesNeed = cities.filter((city) => {
    if (isPinyin) {
      return city.pinyin.startsWith(keyword)||city.initial.startsWith(keyword);
    } else {
      return city.name.startsWith(cityData.trim());
    }
  });

  return citiesNeed.slice(0, 10);
};
